### PR TITLE
345 add quiet switch

### LINKED ISSUE #345: Have a summary option
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description
Add a summary option. On huge databases the output log is swamped with messages of "Total batches received..." and "Written batch..." messages. A summary option would be dropping those and just have start/stop msgs, or any problems in between.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

N/A

### 2. What you expected to happen
Have a summary mode.

### 3. What actually happened
Huge output logs.

## Environment details

- Version(s) that are affected by this issue.
    > 2.6.1 (master)
- Node.js version
    > 14

### PR DESCRIPTION
**Pull request by ricellis**
## Checklist

- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](../blob/master/DCO1.1.txt)
- [x] Added tests for code changes _or_ test/build only changes
- [x] Updated the change log file (`CHANGES.md`|`CHANGELOG.md`) _or_ test/build only changes
- [x] Completed the PR template below:

## Description

Add a quiet switch to reduce the output from couchbackup and couchrestore CLI commands.

Fixes #345

## Approach

Split the `debug` instance between the summary messages (the original `couchbackup:backup` and `couchbackup:restore` namespaces) and the batch messages (new `couchbackup:backup:batch` and `couchbackup:restore:batch` namespaces.
Leave the summary message namespaces always `enabled:true` (as before).
Make the new namepsaces `enabled:true` by default to preserve existing behaviour, but make it settable via the quiet parameter.

## Schema & API Changes

- New `-q`, `--quiet` CLI parameter or `COUCH_QUIET` env var - note this is CLI only, the API does not log these messages (it sends the events instead so it is up to the user to handle/log events as desired).

## Security and Privacy

- "No change"

## Testing

- Added new tests for the quiet option:
    - `respects the COUCH_QUIET env variable if the --quiet backup command-line parameter is missing`
    - `respects the backup --quiet command-line parameter`
    - `respects the COUCH_QUIET env variable if the --quiet restorer command-line parameter is missing`
    - `respects the restore --quiet command-line parameter`
- Added new tests for the resume option which were missing from the set
    - `respects the COUCH_RESUME env variable if the --resume backup command-line parameter is missing`
    - `respects the backup --resume command-line parameter`

## Monitoring and Logging

- Default output remains the same, but `-q`, `--quiet` or `COUCH_QUIET` can be used to suppress batch messages for CLI.

### CODE REVIEW

**Review by eiri — APPROVED** [review]

**Review by emlaver — COMMENTED** [review]
Looks good, have you verified that the new debug options are working locally?

**Comment by ricellis** [comment]
>have you verified that the new debug options are working locally?

yes 😄 

without quiet mode:

`./bin/couchbackup.bin.js --url 'https://examples.cloudant.com' --db animaldb > /dev/null `
```
================================================================================
Performing backup on https://examples.cloudant.com/animaldb using configuration:
{
  "bufferSize": 500,
  "log": "/var/folders/w2/j4ccs8ms26j94l9kljk3hmmh0000gn/T/tmp-12566-fdjO3EIAF4hI",
  "mode": "full",
  "parallelism": 5,
  "requestTimeout": 120000,
  "resume": false
}
================================================================================
  couchbackup:backup Fetching all database changes... +0ms
  couchbackup:backup:batch Total batches received: 1 +0ms
  couchbackup:backup:batch Written batch ID: 0 Total document revisions written: 15 Time: 1.289 +519ms
  couchbackup:backup Finished - Total document revisions written: 15 +2s
```

and with quiet mode:

` ./bin/couchbackup.bin.js --url 'https://examples.cloudant.com' --db animaldb -q > /dev/null`
```
================================================================================
Performing backup on https://examples.cloudant.com/animaldb using configuration:
{
  "bufferSize": 500,
  "log": "/var/folders/w2/j4ccs8ms26j94l9kljk3hmmh0000gn/T/tmp-12572-Ix3pLc0Nrtxw",
  "mode": "full",
  "parallelism": 5,
  "requestTimeout": 120000,
  "resume": false
}
================================================================================
  couchbackup:backup Fetching all database changes... +0ms
  couchbackup:backup Finished - Total document revisions written: 15 +2s
  ```

**Review by emlaver — APPROVED** [review]
Looks good!

**Comment by ricellis** [comment]
FTR I did check restore as well:
`cat backup | ./bin/couchrestore.bin.js --url 'https://***.cloudant.com' --db restoretest`
```
================================================================================
Performing restore on https://***.cloudant.com/restoretest using configuration:
{
  "bufferSize": 500,
  "parallelism": 5,
  "requestTimeout": 120000
}
================================================================================
  couchbackup:restore:batch restored 15 +0ms
  couchbackup:restore finished { total: 15 } +0ms
```

and with quiet:
`cat backup | ./bin/couchrestore.bin.js --url 'https://***.cloudant.com' --db restoretest2 -q`
```
================================================================================
Performing restore on https://***.cloudant.com/restoretest2 using configuration:
{
  "bufferSize": 500,
  "parallelism": 5,
  "requestTimeout": 120000
}
================================================================================
  couchbackup:restore finished { total: 15 } +0ms`
```

**Pull request merged**
